notifications:
  email:
    recipients: ['jost.prevc@gmail.com']
  pushover:
    recipients: ['ukdwndomjog3swwos57umfydpsa2sk']
message_body_format: "Query: {query}\nURL: {url}\nPrice: {price}\n"
urls:
  'pet_prijateljev': https://www.bolha.com/?ctl=search_ads&keywords=pet+prijateljev
  'enid_blyton': https://www.bolha.com/?ctl=search_ads&keywords=enid%20blyton
