email_recipients: ['jost.prevc@gmail.com']
email_body_format: "Type: {type}\nID/URL: {id_url}\n"
urls:
  login: 'https://carobni-svet.com/portal/parents/login'
  photos: 'https://carobni-svet.com/za-starse-fotodnevnik'
  blog: 'https://carobni-svet.com/za-starse-blog'