notifications:
  email:
    recipients: ['jost.prevc@gmail.com']
    message_body_format: "Type: {type}\nID/URL: {url}\n"
  pushover:
    recipients: ['ukdwndomjog3swwos57umfydpsa2sk']
    message_body_format: "Type: {type}\n"
    send_separately: True
urls:
  login: 'https://carobni-svet.com/portal/parents/login'
  photos: 'https://carobni-svet.com/za-starse-fotodnevnik'
  blog: 'https://carobni-svet.com/za-starse-blog'